#!/bin/sh
#-
# Copyright (c) 2011 Nathan Whitehorn
# Copyright (c) 2024 The FreeBSD Foundation
# All rights reserved.
#
# Redistribution and use in source and binary forms, with or without
# modification, are permitted provided that the following conditions
# are met:
# 1. Redistributions of source code must retain the above copyright
#    notice, this list of conditions and the following disclaimer.
# 2. Redistributions in binary form must reproduce the above copyright
#    notice, this list of conditions and the following disclaimer in the
#    documentation and/or other materials provided with the distribution.
#
# THIS SOFTWARE IS PROVIDED BY THE AUTHOR AND CONTRIBUTORS ``AS IS'' AND
# ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
# IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
# ARE DISCLAIMED.  IN NO EVENT SHALL THE AUTHOR OR CONTRIBUTORS BE LIABLE
# FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
# DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS
# OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION)
# HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
# LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY
# OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF
# SUCH DAMAGE.
#

test -f $BSDINSTALL_DISTDIR/MANIFEST || exit 0

BSDCFG_SHARE="/usr/share/bsdconfig"
. $BSDCFG_SHARE/common.subr || exit 1

: ${TMPDIR:="/tmp"}
: ${BSDDIALOG:="bsddialog"}
: ${BSDINSTALL_TMPCHECKSUM:="${TMPDIR}/bsdinstall_checksum"}

checksum()
{
	percentage=0
	for dist in $DISTRIBUTIONS; do
		echo "XXX"
		echo "$percentage"
		echo
		echo "$dist: validating checksum..."

		CK=`sha256 -q $BSDINSTALL_DISTDIR/$dist`
		awk -v checksum=$CK -v dist=$dist -v found=0 '{
			if (dist == $1) {
				found = 1
				if (checksum == $2)
					exit(0)
				else
					exit(2)
			}
		} END {if (!found) exit(1);}' $BSDINSTALL_DISTDIR/MANIFEST

		CK_VALID=$?
		if [ $CK_VALID -le 1 ]; then
			percentage=$((percentage + 100/$(echo $DISTRIBUTIONS | wc -w) ))
			echo "XXX"
			echo "$percentage"
			echo
			if [ $CK_VALID -eq 0 ]; then
				echo "$dist: checksum validated"
			else
				echo "$dist: checksum not found"
			fi
		else
			case $(/bin/freebsd-version -u) in
			*-ALPHA*|*-CURRENT|*-STABLE|*-PRERELEASE)
				echo "EOF"
				echo "The checksum for $dist does not match. It may have become corrupted, or it may be from a newer version of $OSNAME. Please check for a newer snapshot." > "$BSDINSTALL_TMPCHECKSUM"
				;;
			*)
				echo "EOF"
				echo "The checksum for $dist does not match. It may have become corrupted, and should be redownloaded." > "$BSDINSTALL_TMPCHECKSUM"
				;;
			esac
			exit 1
		fi
	done
	echo "EOF"
}

checksum | $BSDDIALOG --backtitle "$OSNAME Installer" \
		 --title "Checksum Verification" \
		 --gauge "\nVerifying checksums of selected distributions.\n" \
		 0 0 0

if [ -f "$BSDINSTALL_TMPCHECKSUM" ]; then
	$BSDDIALOG --backtitle "$OSNAME Installer" --title "Error" \
	    --msgbox "$(cat "$BSDINSTALL_TMPCHECKSUM")" 0 0
	rm -f "$BSDINSTALL_TMPCHECKSUM"
	exit 1
fi
exit 0
