SBOM_DESC=	Modular user authentication facility
SBOM_VERSION=	20250531
SBOM_LICENSE=	BSD-3-Clause
SBOM_COPYRIGHT=	Copyright (c) 2002-2003 Networks Associates Technology, Inc.
SBOM_URL=	https://openpam.org
SBOM_SOURCE=	https://git.des.dev/OpenPAM/OpenPAM
