SBOM_DESC=	Powerful command-line packet analyzer
SBOM_VERSION=	4.99.5
SBOM_LICENSE=	BSD-3-Clause
SBOM_URL=	https://www.tcpdump.org
SBOM_SOURCE=	https://fossies.org/linux/misc/${SBOM_NAME}-${SBOM_VERSION}.tar.gz
