SBOM_NAME=	${PACKAGE}
SBOM_DESC=	Yellow Pages (YP) / Network Information Service (NIS)
SBOM_LICENSE=	BSD-3-Clause
SBOM_COPYRIGHT=	Copyright (c) 1988, 1991, 1993, 1995 The Regents of the University of California
