#ifndef _PKG_CONFIG_H
#define _PKG_CONFIG_H
#define DEFAULT_COMPRESSION TZS
#define HAVE_ARC4RANDOM 1
/* #undef HAVE_ARC4RANDOM_STIR */
#define HAVE_ARCHIVE_READ_OPEN 1
#define HAVE_ARCHIVE_WRITE_ADD_FILTER_ZSTD 1
#define HAVE_ATOMIC_BUILTINS 1
#define HAVE_BZ2_BZREADOPEN 1
#define HAVE_CHFLAGSAT 1
#define HAVE_CLOSEFROM 1
#define HAVE_COPY_FILE_RANGE 1
#define HAVE_DECL_BE16DEC 1
#define HAVE_DECL_BE16ENC 1
#define HAVE_DECL_BE32DEC 1
#define HAVE_DECL_BE32ENC 1
#define HAVE_DECL_BE64DEC 1
#define HAVE_DECL_BE64ENC 1
#define HAVE_DECL_HUMANIZE_NUMBER 1
#define HAVE_DECL_LE16DEC 1
#define HAVE_DECL_LE16ENC 1
#define HAVE_DECL_LE32DEC 1
#define HAVE_DECL_LE32ENC 1
#define HAVE_DECL_LE64DEC 1
#define HAVE_DECL_LE64ENC 1
#define HAVE_DLCLOSE 1
/* #undef HAVE_ELF_NOTE */
#define HAVE_ENDIAN_H 1
#define HAVE_FFLAGSTOSTR 1
#define HAVE_FOPENCOOKIE 1
#define HAVE_FTS_OPEN 1
#define HAVE_FUNOPEN 1
#define HAVE_GELF_GETEHDR 1
#define HAVE_GELF_H 1
#define HAVE_GETPROGNAME 1
#define HAVE_HUMANIZE_NUMBER 1
#define HAVE_JAIL_GETID 1
#define HAVE_LIBELF 1
#define HAVE_LIBELF_H 1
#define HAVE_LIBJAIL 1
#define HAVE_LIBMD 1
#define HAVE_LIBUTIL 1
#define HAVE_LIBUTIL_H 1
#define HAVE_LZMA_VERSION_STRING 1
#define HAVE_MEMMOVE 1
#define HAVE_NETINET_IN_H 1
#define HAVE_PKG_CONFIG 1
#define HAVE_PKG_OPENSSL 1
#define HAVE_PREAD 1
/* #undef HAVE_PROC_PID */
#define HAVE_PWRITE 1
#define HAVE_SHA256_DATA 1
#define HAVE_STATIC 1
#define HAVE_STDLIB_H 1
#define HAVE_STRCHRNUL 1
#define HAVE_STRTOFFLAGS 1
#define HAVE_STRTONUM 1
#define HAVE_STRUCT_SOCKADDR_IN_SIN_LEN 1
#define HAVE_STRUCT_STAT_ST_FLAGS 1
#define HAVE_STRUCT_STAT_ST_MTIM 1
#define HAVE_SYS_ENDIAN_H 1
#define HAVE_SYS_STAT_H 1
#define HAVE_USLEEP 1
#define HAVE_UTIMENSAT 1
#define HAVE_ZLIBVERSION 1
#define HAVE_ZSTD_VERSIONNUMBER 1
#define HAVE___RES_SETSERVERS 1
#endif
