SBOM_NAME=	${PACKAGE}
SBOM_DESC=	Network Time Protocol (NTP) daemon
SBOM_VERSION=	ntp-4.2.8p18
SBOM_URL=	https://www.ntp.org
SBOM_SOURCE=	https://downloads.nwtime.org/ntp/4.2.8/${SBOM_VERSION}.tar.gz
SBOM_COPYRIGHT=	Network Time Foundation 2011-2024
