SBOM_DESC=	Library for elliptic curves based cryptography (ECC)
SBOM_LICENSE=	BSD-2-Clause AND GPL-2.0-or-later
SBOM_COPYRIGHT=	Copyright (C) 2017-2023 Ryad BENADJILA, Arnaud EBALARD, Jean-Pierre FLORI
SBOM_URL=	https://github.com/libecc/libecc
