SBOM_NAME=	${PACKAGE}
SBOM_DESC=	OpenBSD packet filter
SBOM_LICENSE=	BSD-3-Clause
SBOM_COPYRIGHT=	Copyright (c) 2001 Daniel Hartmeier
SBOM_URL=	https://www.openbsd.org
SBOM_SOURCE=	https://cvsweb.openbsd.org/src
